services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfileflask
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:password@mariadb/students_db

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfilemariadb
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students_db

