services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:password@mariadb/students_db

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile.mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students_db
    volumes:
      - mariadb-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    volumes:
      - /var/lib/jenkins/workspace/Trabalho-DevOps-2303469/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - mysqld_exporter
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  mysqld_exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "user:password@(mariadb:3306)/"
    depends_on:
      - mariadb

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  mariadb-data:
