# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

# Copiar o arquivo de dependências
COPY requirements.txt /app/requirements.txt

# Instalar as dependências
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copiar o código da aplicação e testes
COPY . /app/

# Expor a porta em que o Flask vai rodar
EXPOSE 5000

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]

