# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

# Copiar o arquivo de dependências
COPY requirements.txt requirements.txt

# Instalar as dependências do requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o arquivo do app
COPY app.py /app/

# Expor a porta em que o Flask vai rodar
EXPOSE 5000

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]

